# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\Program\Eric6\MailMgr\config_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.5
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.setWindowModality(QtCore.Qt.ApplicationModal)
        Dialog.resize(681, 492)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        Dialog.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon/hello.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        Dialog.setSizeGripEnabled(True)
        Dialog.setModal(False)
        self.tabWidget = QtWidgets.QTabWidget(Dialog)
        self.tabWidget.setGeometry(QtCore.QRect(10, 10, 651, 471))
        self.tabWidget.setObjectName("tabWidget")
        self.tab_ok = QtWidgets.QWidget()
        self.tab_ok.setObjectName("tab_ok")
        self.blackList = QtWidgets.QTableWidget(self.tab_ok)
        self.blackList.setGeometry(QtCore.QRect(10, 20, 271, 391))
        self.blackList.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.blackList.setStyleSheet("QHeaderView::section{background:rgb(85, 170, 255)};")
        self.blackList.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.blackList.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.blackList.setTextElideMode(QtCore.Qt.ElideMiddle)
        self.blackList.setObjectName("blackList")
        self.blackList.setColumnCount(1)
        self.blackList.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.blackList.setHorizontalHeaderItem(0, item)
        self.mailno = QtWidgets.QLineEdit(self.tab_ok)
        self.mailno.setGeometry(QtCore.QRect(320, 80, 171, 21))
        self.mailno.setObjectName("mailno")
        self.addBtn1 = QtWidgets.QPushButton(self.tab_ok)
        self.addBtn1.setGeometry(QtCore.QRect(320, 130, 71, 31))
        self.addBtn1.setObjectName("addBtn1")
        self.saveBtn1 = QtWidgets.QPushButton(self.tab_ok)
        self.saveBtn1.setGeometry(QtCore.QRect(420, 130, 71, 31))
        self.saveBtn1.setObjectName("saveBtn1")
        self.checkLocal = QtWidgets.QCheckBox(self.tab_ok)
        self.checkLocal.setGeometry(QtCore.QRect(340, 350, 131, 21))
        self.checkLocal.setChecked(True)
        self.checkLocal.setObjectName("checkLocal")
        self.groupBox = QtWidgets.QGroupBox(self.tab_ok)
        self.groupBox.setGeometry(QtCore.QRect(310, 270, 321, 151))
        self.groupBox.setObjectName("groupBox")
        self.okBtn1 = QtWidgets.QPushButton(self.groupBox)
        self.okBtn1.setGeometry(QtCore.QRect(220, 70, 71, 31))
        self.okBtn1.setObjectName("okBtn1")
        self.checkDb = QtWidgets.QCheckBox(self.groupBox)
        self.checkDb.setGeometry(QtCore.QRect(30, 120, 141, 21))
        self.checkDb.setObjectName("checkDb")
        self.checkBlack = QtWidgets.QCheckBox(self.groupBox)
        self.checkBlack.setGeometry(QtCore.QRect(30, 40, 131, 21))
        self.checkBlack.setChecked(False)
        self.checkBlack.setObjectName("checkBlack")
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab_ok)
        self.groupBox_2.setGeometry(QtCore.QRect(310, 50, 321, 151))
        self.groupBox_2.setObjectName("groupBox_2")
        self.domain_1 = QtWidgets.QComboBox(self.groupBox_2)
        self.domain_1.setGeometry(QtCore.QRect(180, 30, 91, 21))
        self.domain_1.setObjectName("domain_1")
        self.domain_1.addItem("")
        self.domain_1.setItemText(0, "")
        self.domain_1.addItem("")
        self.domain_1.addItem("")
        self.domain_1.addItem("")
        self.domain_1.addItem("")
        self.domain_1.addItem("")
        self.domain_1.addItem("")
        self.delBtn1 = QtWidgets.QPushButton(self.tab_ok)
        self.delBtn1.setGeometry(QtCore.QRect(320, 210, 71, 31))
        self.delBtn1.setObjectName("delBtn1")
        self.groupBox.raise_()
        self.groupBox_2.raise_()
        self.blackList.raise_()
        self.mailno.raise_()
        self.addBtn1.raise_()
        self.saveBtn1.raise_()
        self.checkLocal.raise_()
        self.delBtn1.raise_()
        self.tabWidget.addTab(self.tab_ok, "")
        self.tab_no = QtWidgets.QWidget()
        self.tab_no.setObjectName("tab_no")
        self.whiteList = QtWidgets.QTableWidget(self.tab_no)
        self.whiteList.setGeometry(QtCore.QRect(10, 20, 271, 391))
        self.whiteList.setStyleSheet("QHeaderView::section{background:rgb(85, 170, 255)};\n"
"")
        self.whiteList.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.whiteList.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.whiteList.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.whiteList.setTextElideMode(QtCore.Qt.ElideMiddle)
        self.whiteList.setObjectName("whiteList")
        self.whiteList.setColumnCount(1)
        self.whiteList.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.whiteList.setHorizontalHeaderItem(0, item)
        self.mailok = QtWidgets.QLineEdit(self.tab_no)
        self.mailok.setGeometry(QtCore.QRect(320, 80, 171, 21))
        self.mailok.setObjectName("mailok")
        self.domain_2 = QtWidgets.QComboBox(self.tab_no)
        self.domain_2.setGeometry(QtCore.QRect(490, 80, 91, 21))
        self.domain_2.setObjectName("domain_2")
        self.domain_2.addItem("")
        self.domain_2.setItemText(0, "")
        self.domain_2.addItem("")
        self.domain_2.addItem("")
        self.domain_2.addItem("")
        self.domain_2.addItem("")
        self.domain_2.addItem("")
        self.domain_2.addItem("")
        self.addBtn2 = QtWidgets.QPushButton(self.tab_no)
        self.addBtn2.setGeometry(QtCore.QRect(320, 130, 71, 31))
        self.addBtn2.setObjectName("addBtn2")
        self.saveBtn2 = QtWidgets.QPushButton(self.tab_no)
        self.saveBtn2.setGeometry(QtCore.QRect(420, 130, 71, 31))
        self.saveBtn2.setObjectName("saveBtn2")
        self.delBtn2 = QtWidgets.QPushButton(self.tab_no)
        self.delBtn2.setGeometry(QtCore.QRect(320, 210, 71, 31))
        self.delBtn2.setObjectName("delBtn2")
        self.groupBox_3 = QtWidgets.QGroupBox(self.tab_no)
        self.groupBox_3.setGeometry(QtCore.QRect(310, 50, 291, 151))
        self.groupBox_3.setObjectName("groupBox_3")
        self.groupBox_4 = QtWidgets.QGroupBox(self.tab_no)
        self.groupBox_4.setGeometry(QtCore.QRect(310, 270, 321, 151))
        self.groupBox_4.setObjectName("groupBox_4")
        self.okBtn2 = QtWidgets.QPushButton(self.groupBox_4)
        self.okBtn2.setGeometry(QtCore.QRect(230, 60, 71, 31))
        self.okBtn2.setObjectName("okBtn2")
        self.checkWhite = QtWidgets.QCheckBox(self.groupBox_4)
        self.checkWhite.setGeometry(QtCore.QRect(40, 40, 101, 21))
        self.checkWhite.setChecked(False)
        self.checkWhite.setObjectName("checkWhite")
        self.checkLocal_2 = QtWidgets.QCheckBox(self.groupBox_4)
        self.checkLocal_2.setGeometry(QtCore.QRect(40, 80, 131, 21))
        self.checkLocal_2.setChecked(True)
        self.checkLocal_2.setObjectName("checkLocal_2")
        self.groupBox_3.raise_()
        self.whiteList.raise_()
        self.mailok.raise_()
        self.domain_2.raise_()
        self.addBtn2.raise_()
        self.saveBtn2.raise_()
        self.delBtn2.raise_()
        self.groupBox_4.raise_()
        self.tabWidget.addTab(self.tab_no, "")

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "收信规则"))
        item = self.blackList.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "邮件地址"))
        self.addBtn1.setText(_translate("Dialog", "添加"))
        self.saveBtn1.setText(_translate("Dialog", "保存"))
        self.checkLocal.setText(_translate("Dialog", "开启本地过滤规则"))
        self.groupBox.setTitle(_translate("Dialog", "过滤规则"))
        self.okBtn1.setText(_translate("Dialog", "确定"))
        self.checkDb.setText(_translate("Dialog", "开启数据库过滤规则"))
        self.checkBlack.setText(_translate("Dialog", "开启黑名单过滤"))
        self.groupBox_2.setTitle(_translate("Dialog", "手动添加"))
        self.domain_1.setItemText(1, _translate("Dialog", "@163.com"))
        self.domain_1.setItemText(2, _translate("Dialog", "@gmail.com"))
        self.domain_1.setItemText(3, _translate("Dialog", "@hotmail.com"))
        self.domain_1.setItemText(4, _translate("Dialog", "@qq.com"))
        self.domain_1.setItemText(5, _translate("Dialog", "@126.com"))
        self.domain_1.setItemText(6, _translate("Dialog", "@yeah.net"))
        self.delBtn1.setText(_translate("Dialog", "删除"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_ok), _translate("Dialog", "黑名单设置"))
        item = self.whiteList.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "邮件地址"))
        self.domain_2.setItemText(1, _translate("Dialog", "@163.com"))
        self.domain_2.setItemText(2, _translate("Dialog", "@gmail.com"))
        self.domain_2.setItemText(3, _translate("Dialog", "@hotmail.com"))
        self.domain_2.setItemText(4, _translate("Dialog", "@qq.com"))
        self.domain_2.setItemText(5, _translate("Dialog", "@126.com"))
        self.domain_2.setItemText(6, _translate("Dialog", "@yeah.net"))
        self.addBtn2.setText(_translate("Dialog", "添加"))
        self.saveBtn2.setText(_translate("Dialog", "保存"))
        self.delBtn2.setText(_translate("Dialog", "删除"))
        self.groupBox_3.setTitle(_translate("Dialog", "手动添加"))
        self.groupBox_4.setTitle(_translate("Dialog", "过滤规则"))
        self.okBtn2.setText(_translate("Dialog", "确定"))
        self.checkWhite.setText(_translate("Dialog", "开启白名单"))
        self.checkLocal_2.setText(_translate("Dialog", "开启本地过滤规则"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_no), _translate("Dialog", "白名单设置"))

import mailmgr_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

