# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\Program\Eric6\MailMgr\mainWin.ui'
#
# Created by: PyQt5 UI code generator 5.5
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.WindowModal)
        MainWindow.resize(969, 694)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        MainWindow.setFont(font)
        MainWindow.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon/hello.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralWidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 961, 661))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.tabWidget.setFont(font)
        self.tabWidget.setFocusPolicy(QtCore.Qt.TabFocus)
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.South)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_1 = QtWidgets.QWidget()
        self.tab_1.setObjectName("tab_1")
        self.groupBox = QtWidgets.QGroupBox(self.tab_1)
        self.groupBox.setGeometry(QtCore.QRect(10, 30, 931, 141))
        self.groupBox.setObjectName("groupBox")
        self.smtpServer = QtWidgets.QComboBox(self.groupBox)
        self.smtpServer.setGeometry(QtCore.QRect(110, 40, 131, 31))
        self.smtpServer.setEditable(True)
        self.smtpServer.setObjectName("smtpServer")
        self.smtpServer.addItem("")
        self.smtpServer.addItem("")
        self.smtpServer.addItem("")
        self.smtpServer.addItem("")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(20, 40, 81, 21))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(20, 100, 61, 21))
        self.label_2.setObjectName("label_2")
        self.fromMail = QtWidgets.QLineEdit(self.groupBox)
        self.fromMail.setGeometry(QtCore.QRect(90, 100, 141, 21))
        self.fromMail.setObjectName("fromMail")
        self.domain_1 = QtWidgets.QComboBox(self.groupBox)
        self.domain_1.setGeometry(QtCore.QRect(230, 100, 91, 21))
        self.domain_1.setObjectName("domain_1")
        self.domain_1.addItem("")
        self.domain_1.setItemText(0, "")
        self.domain_1.addItem("")
        self.domain_1.addItem("")
        self.domain_1.addItem("")
        self.domain_1.addItem("")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(390, 100, 51, 21))
        self.label_3.setObjectName("label_3")
        self.sendPwd = QtWidgets.QLineEdit(self.groupBox)
        self.sendPwd.setGeometry(QtCore.QRect(440, 100, 141, 20))
        self.sendPwd.setEchoMode(QtWidgets.QLineEdit.Password)
        self.sendPwd.setObjectName("sendPwd")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(390, 40, 61, 16))
        self.label_4.setObjectName("label_4")
        self.sender = QtWidgets.QLineEdit(self.groupBox)
        self.sender.setGeometry(QtCore.QRect(440, 40, 141, 20))
        self.sender.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.sender.setObjectName("sender")
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab_1)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 190, 581, 111))
        self.groupBox_2.setObjectName("groupBox_2")
        self.label_5 = QtWidgets.QLabel(self.groupBox_2)
        self.label_5.setGeometry(QtCore.QRect(20, 30, 61, 21))
        self.label_5.setObjectName("label_5")
        self.toMail = QtWidgets.QLineEdit(self.groupBox_2)
        self.toMail.setGeometry(QtCore.QRect(90, 30, 201, 21))
        self.toMail.setObjectName("toMail")
        self.domain_2 = QtWidgets.QComboBox(self.groupBox_2)
        self.domain_2.setGeometry(QtCore.QRect(290, 30, 91, 21))
        self.domain_2.setObjectName("domain_2")
        self.domain_2.addItem("")
        self.domain_2.setItemText(0, "")
        self.domain_2.addItem("")
        self.domain_2.addItem("")
        self.domain_2.addItem("")
        self.domain_2.addItem("")
        self.label_6 = QtWidgets.QLabel(self.groupBox_2)
        self.label_6.setGeometry(QtCore.QRect(20, 80, 61, 16))
        self.label_6.setObjectName("label_6")
        self.receiver = QtWidgets.QLineEdit(self.groupBox_2)
        self.receiver.setGeometry(QtCore.QRect(90, 80, 141, 20))
        self.receiver.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.receiver.setObjectName("receiver")
        self.groupBox_3 = QtWidgets.QGroupBox(self.tab_1)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 320, 581, 281))
        self.groupBox_3.setObjectName("groupBox_3")
        self.label_7 = QtWidgets.QLabel(self.groupBox_3)
        self.label_7.setGeometry(QtCore.QRect(20, 40, 31, 21))
        self.label_7.setObjectName("label_7")
        self.mailSub = QtWidgets.QLineEdit(self.groupBox_3)
        self.mailSub.setGeometry(QtCore.QRect(60, 40, 211, 21))
        self.mailSub.setObjectName("mailSub")
        self.mailContent = QtWidgets.QTextEdit(self.groupBox_3)
        self.mailContent.setGeometry(QtCore.QRect(60, 90, 491, 101))
        self.mailContent.setObjectName("mailContent")
        self.label_8 = QtWidgets.QLabel(self.groupBox_3)
        self.label_8.setGeometry(QtCore.QRect(20, 90, 31, 21))
        self.label_8.setObjectName("label_8")
        self.addBtn = QtWidgets.QPushButton(self.groupBox_3)
        self.addBtn.setGeometry(QtCore.QRect(390, 200, 71, 21))
        self.addBtn.setObjectName("addBtn")
        self.filePath = QtWidgets.QLineEdit(self.groupBox_3)
        self.filePath.setGeometry(QtCore.QRect(60, 200, 321, 20))
        self.filePath.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.filePath.setObjectName("filePath")
        self.pushBtn = QtWidgets.QPushButton(self.groupBox_3)
        self.pushBtn.setGeometry(QtCore.QRect(60, 240, 51, 31))
        self.pushBtn.setObjectName("pushBtn")
        self.groupBox_6 = QtWidgets.QGroupBox(self.tab_1)
        self.groupBox_6.setGeometry(QtCore.QRect(630, 190, 311, 411))
        self.groupBox_6.setObjectName("groupBox_6")
        self.statusList = QtWidgets.QListWidget(self.groupBox_6)
        self.statusList.setGeometry(QtCore.QRect(10, 30, 291, 371))
        self.statusList.setObjectName("statusList")
        self.testBtn = QtWidgets.QPushButton(self.tab_1)
        self.testBtn.setGeometry(QtCore.QRect(870, 10, 75, 23))
        self.testBtn.setObjectName("testBtn")
        self.tabWidget.addTab(self.tab_1, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.popServer = QtWidgets.QComboBox(self.tab_2)
        self.popServer.setGeometry(QtCore.QRect(110, 70, 131, 31))
        self.popServer.setEditable(True)
        self.popServer.setObjectName("popServer")
        self.popServer.addItem("")
        self.popServer.addItem("")
        self.popServer.addItem("")
        self.popServer.addItem("")
        self.groupBox_4 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_4.setGeometry(QtCore.QRect(10, 20, 921, 131))
        self.groupBox_4.setObjectName("groupBox_4")
        self.label_10 = QtWidgets.QLabel(self.groupBox_4)
        self.label_10.setGeometry(QtCore.QRect(20, 60, 71, 16))
        self.label_10.setObjectName("label_10")
        self.popMail = QtWidgets.QLineEdit(self.groupBox_4)
        self.popMail.setGeometry(QtCore.QRect(390, 40, 141, 21))
        self.popMail.setObjectName("popMail")
        self.domain_3 = QtWidgets.QComboBox(self.groupBox_4)
        self.domain_3.setGeometry(QtCore.QRect(530, 40, 91, 21))
        self.domain_3.setObjectName("domain_3")
        self.domain_3.addItem("")
        self.domain_3.setItemText(0, "")
        self.domain_3.addItem("")
        self.domain_3.addItem("")
        self.domain_3.addItem("")
        self.domain_3.addItem("")
        self.label_9 = QtWidgets.QLabel(self.groupBox_4)
        self.label_9.setGeometry(QtCore.QRect(320, 40, 61, 16))
        self.label_9.setObjectName("label_9")
        self.label_12 = QtWidgets.QLabel(self.groupBox_4)
        self.label_12.setGeometry(QtCore.QRect(320, 90, 61, 16))
        self.label_12.setObjectName("label_12")
        self.receivePwd = QtWidgets.QLineEdit(self.groupBox_4)
        self.receivePwd.setGeometry(QtCore.QRect(390, 90, 141, 21))
        self.receivePwd.setEchoMode(QtWidgets.QLineEdit.Password)
        self.receivePwd.setObjectName("receivePwd")
        self.groupBox_5 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_5.setGeometry(QtCore.QRect(10, 170, 631, 441))
        self.groupBox_5.setObjectName("groupBox_5")
        self.popList = QtWidgets.QTableWidget(self.groupBox_5)
        self.popList.setGeometry(QtCore.QRect(20, 60, 601, 111))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.popList.setFont(font)
        self.popList.setStyleSheet("QHeaderView::section{background:rgb(85, 170, 255)};")
        self.popList.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.popList.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.popList.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.popList.setObjectName("popList")
        self.popList.setColumnCount(3)
        self.popList.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.popList.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.popList.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.popList.setHorizontalHeaderItem(2, item)
        self.popContent = QtWidgets.QTextBrowser(self.groupBox_5)
        self.popContent.setGeometry(QtCore.QRect(20, 210, 591, 171))
        self.popContent.setObjectName("popContent")
        self.label_11 = QtWidgets.QLabel(self.groupBox_5)
        self.label_11.setGeometry(QtCore.QRect(20, 190, 41, 16))
        self.label_11.setObjectName("label_11")
        self.pullBtn = QtWidgets.QPushButton(self.groupBox_5)
        self.pullBtn.setGeometry(QtCore.QRect(20, 390, 51, 31))
        self.pullBtn.setObjectName("pullBtn")
        self.label_13 = QtWidgets.QLabel(self.groupBox_5)
        self.label_13.setGeometry(QtCore.QRect(20, 32, 54, 20))
        self.label_13.setObjectName("label_13")
        self.extraBtn = QtWidgets.QPushButton(self.groupBox_5)
        self.extraBtn.setGeometry(QtCore.QRect(90, 390, 51, 31))
        self.extraBtn.setObjectName("extraBtn")
        self.groupBox_7 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_7.setGeometry(QtCore.QRect(670, 180, 261, 431))
        self.groupBox_7.setObjectName("groupBox_7")
        self.popStatus = QtWidgets.QListWidget(self.groupBox_7)
        self.popStatus.setGeometry(QtCore.QRect(10, 30, 241, 391))
        self.popStatus.setObjectName("popStatus")
        self.popTest = QtWidgets.QPushButton(self.tab_2)
        self.popTest.setGeometry(QtCore.QRect(870, 0, 61, 23))
        self.popTest.setObjectName("popTest")
        self.groupBox_4.raise_()
        self.popServer.raise_()
        self.groupBox_5.raise_()
        self.groupBox_7.raise_()
        self.popTest.raise_()
        self.tabWidget.addTab(self.tab_2, "")
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 969, 23))
        self.menuBar.setObjectName("menuBar")
        self.config = QtWidgets.QMenu(self.menuBar)
        self.config.setObjectName("config")
        self.file_menu = QtWidgets.QMenu(self.menuBar)
        self.file_menu.setObjectName("file_menu")
        self.quit_menu = QtWidgets.QMenu(self.menuBar)
        self.quit_menu.setObjectName("quit_menu")
        MainWindow.setMenuBar(self.menuBar)
        self.saveFile = QtWidgets.QAction(MainWindow)
        self.saveFile.setObjectName("saveFile")
        self.saveAs = QtWidgets.QAction(MainWindow)
        self.saveAs.setObjectName("saveAs")
        self.file_menu.addSeparator()
        self.file_menu.addSeparator()
        self.menuBar.addAction(self.file_menu.menuAction())
        self.menuBar.addAction(self.config.menuAction())
        self.menuBar.addAction(self.quit_menu.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "邮件收发管理系统"))
        self.groupBox.setTitle(_translate("MainWindow", "发件人信息"))
        self.smtpServer.setItemText(0, _translate("MainWindow", "smtp.163.com"))
        self.smtpServer.setItemText(1, _translate("MainWindow", "smtp.126.com"))
        self.smtpServer.setItemText(2, _translate("MainWindow", "smtp.yeah.net"))
        self.smtpServer.setItemText(3, _translate("MainWindow", "smtp.qq.com"))
        self.label.setText(_translate("MainWindow", "Smtp服务器"))
        self.label_2.setText(_translate("MainWindow", "邮箱账号"))
        self.domain_1.setItemText(1, _translate("MainWindow", "@163.com"))
        self.domain_1.setItemText(2, _translate("MainWindow", "@126.com"))
        self.domain_1.setItemText(3, _translate("MainWindow", "@yeah.net"))
        self.domain_1.setItemText(4, _translate("MainWindow", "@qq.com"))
        self.label_3.setText(_translate("MainWindow", "密  码"))
        self.label_4.setText(_translate("MainWindow", "昵  称"))
        self.groupBox_2.setTitle(_translate("MainWindow", "收件人信息"))
        self.label_5.setText(_translate("MainWindow", "邮箱账号"))
        self.domain_2.setItemText(1, _translate("MainWindow", "@163.com"))
        self.domain_2.setItemText(2, _translate("MainWindow", "@126.com"))
        self.domain_2.setItemText(3, _translate("MainWindow", "@yeah.net"))
        self.domain_2.setItemText(4, _translate("MainWindow", "@qq.com"))
        self.label_6.setText(_translate("MainWindow", "昵  称"))
        self.groupBox_3.setTitle(_translate("MainWindow", "邮件信息"))
        self.label_7.setText(_translate("MainWindow", "主题"))
        self.label_8.setText(_translate("MainWindow", "内容"))
        self.addBtn.setText(_translate("MainWindow", "+添加附件"))
        self.pushBtn.setText(_translate("MainWindow", "发送"))
        self.groupBox_6.setTitle(_translate("MainWindow", "状态信息"))
        self.testBtn.setText(_translate("MainWindow", "测试"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_1), _translate("MainWindow", "写信"))
        self.popServer.setItemText(0, _translate("MainWindow", "pop3.163.com"))
        self.popServer.setItemText(1, _translate("MainWindow", "pop3.126.com"))
        self.popServer.setItemText(2, _translate("MainWindow", "pop3.yeah.net"))
        self.popServer.setItemText(3, _translate("MainWindow", "pop3.qq.com"))
        self.groupBox_4.setTitle(_translate("MainWindow", "用户信息"))
        self.label_10.setText(_translate("MainWindow", "Pop3服务器"))
        self.domain_3.setItemText(1, _translate("MainWindow", "@163.com"))
        self.domain_3.setItemText(2, _translate("MainWindow", "@126.com"))
        self.domain_3.setItemText(3, _translate("MainWindow", "@yeah.net"))
        self.domain_3.setItemText(4, _translate("MainWindow", "@qq.com"))
        self.label_9.setText(_translate("MainWindow", "邮箱账号"))
        self.label_12.setText(_translate("MainWindow", "密    码"))
        self.groupBox_5.setTitle(_translate("MainWindow", "邮件内容"))
        item = self.popList.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "时间"))
        item = self.popList.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "发件人"))
        item = self.popList.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "主题"))
        self.label_11.setText(_translate("MainWindow", "内容"))
        self.pullBtn.setText(_translate("MainWindow", "接收"))
        self.label_13.setText(_translate("MainWindow", "邮件列表"))
        self.extraBtn.setText(_translate("MainWindow", "@附件"))
        self.groupBox_7.setTitle(_translate("MainWindow", "状态信息"))
        self.popTest.setText(_translate("MainWindow", "测试"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "收信"))
        self.config.setTitle(_translate("MainWindow", "设置"))
        self.file_menu.setTitle(_translate("MainWindow", "文件"))
        self.quit_menu.setTitle(_translate("MainWindow", "退出"))
        self.saveFile.setText(_translate("MainWindow", "保存文件"))
        self.saveAs.setText(_translate("MainWindow", "另存为..."))

import mailmgr_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

